# -*- coding: utf-8 -*-
"""Global Wins Essay Reviewer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEnT_TOBEn8-7nlKYJehpImdl3m11VTv
"""

!pip install streamlit
!pip install pyngrok
!pip install nltk

import streamlit as st
import nltk
from nltk.tokenize import sent_tokenize
import random

nltk.download('punkt')

# Writing the Streamlit code to a file called global_wins.py

streamlit_code = """
import streamlit as st
import nltk
from nltk.tokenize import sent_tokenize
import random

# Download necessary resources
nltk.download('punkt')

# Function to restructure the essay based on essay type
def restructure_essay(essay, essay_type):
    sentences = sent_tokenize(essay)

    # Define essay structures for each type
    if essay_type == "Leadership":
        structure = ["Introduction", "First Example", "Second Example", "Third Example", "Conclusion"]
    elif essay_type == "Networking":
        structure = ["Introduction", "First Example", "Second Example", "Third Example", "Conclusion"]
    elif essay_type == "Study in the UK":
        structure = ["Introduction", "First School", "Second School", "Third School", "Conclusion"]
    elif essay_type == "Career Plan":
        structure = ["Introduction", "Short Plan", "Mid Plan", "Long Term Plan", "Conclusion"]
    else:
        return "Invalid Essay Type"

    # Restructure the essay by shuffling sentences
    random.shuffle(sentences)

    # Create a dictionary to store the structured essay
    structured_essay = {section: [] for section in structure}
    section_idx = 0
    for sentence in sentences:
        structured_essay[structure[section_idx]].append(sentence)
        section_idx = (section_idx + 1) % len(structure)  # Loop through sections

    return structured_essay

# Main Streamlit function
def main():
    st.title("Global Wins - Chevening Essay Restructurer")

    # Essay type selection
    essay_type = st.selectbox("Choose Essay Type",
                              ["Leadership", "Networking", "Study in the UK", "Career Plan"])

    # Input essay from user
    essay_input = st.text_area("Paste Your Essay Here:")

    if st.button("Restructure Essay"):
        if essay_input:
            result = restructure_essay(essay_input, essay_type)
            st.write("Restructured Essay:")
            for section, content in result.items():
                st.subheader(section)
                st.write(" ".join(content))
        else:
            st.error("Please enter an essay to restructure.")

if __name__ == "__main__":
    main()
"""

# Write the code to a file
with open("/content/global_wins.py", "w") as file:
    file.write(streamlit_code)

# Confirm the file has been created
"/content/global_wins.py has been created."

# Check the first few lines of the file to verify it was created correctly
with open("/content/global_wins.py", "r") as file:
    print(file.read())

#from pyngrok import ngrok # This import already exists in your code, no need to repeat it.
import os


# **Get your authtoken from ngrok.com and replace 'YOUR_AUTHTOKEN'**
ngrok.set_auth_token('2pU0jMgGE3TOX9nryvBY8I2GdWP_5wwSVHjDT1cpekU2RBSnp')

# Start a tunnel to the Streamlit port. Specify the port with the 'addr' parameter
public_url = ngrok.connect(addr='8501')  # Changed here

from pyngrok import ngrok
import os



# Write the streamlit code to a .py file
streamlit_code = """
import streamlit as st
import nltk
from nltk.tokenize import sent_tokenize
import random

nltk.download('punkt')

def restructure_essay(essay, essay_type):
    sentences = sent_tokenize(essay)

    if essay_type == "Leadership":
        structure = ["Introduction", "First Example", "Second Example", "Third Example", "Conclusion"]
    elif essay_type == "Networking":
        structure = ["Introduction", "First Example", "Second Example", "Third Example", "Conclusion"]
    elif essay_type == "Study in the UK":
        structure = ["Introduction", "First School", "Second School", "Third School", "Conclusion"]
    elif essay_type == "Career Plan":
        structure = ["Introduction", "Short Plan", "Mid Plan", "Long Term Plan", "Conclusion"]
    else:
        return "Invalid Essay Type"

    random.shuffle(sentences)

    structured_essay = {section: [] for section in structure}
    section_idx = 0
    for sentence in sentences:
        structured_essay[structure[section_idx]].append(sentence)
        section_idx = (section_idx + 1) % len(structure)

    return structured_essay

def main():
    st.title("Global Wins - Chevening Essay Restructurer")

    essay_type = st.selectbox("Choose Essay Type", ["Leadership", "Networking", "Study in the UK", "Career Plan"])

    essay_input = st.text_area("Paste Your Essay Here:")

    if st.button("Restructure Essay"):
        if essay_input:
            result = restructure_essay(essay_input, essay_type)
            st.write("Restructured Essay:")
            for section, content in result.items():
                st.subheader(section)
                st.write(" ".join(content))
        else:
            st.error("Please enter an essay to restructure.")

if __name__ == "__main__":
    main()
"""

# Write to a file and run Streamlit
with open("global_wins.py", "w") as file:
    file.write(streamlit_code)

# Run the app
os.system("streamlit run global_wins.py &")

# Display the public URL
public_url

